# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View_myreservation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Query import Query


class Ui_View_myreservation(object):
    def setupUi(self, View_myreservation, View_system):
        self.systemView = View_system

        View_myreservation.setObjectName("View_myreservation")
        View_myreservation.resize(711, 551)
        self.centralwidget = QtWidgets.QWidget(View_myreservation)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.widget_2)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 18)
        View_myreservation.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(View_myreservation)
        self.statusbar.setObjectName("statusbar")
        View_myreservation.setStatusBar(self.statusbar)

        self.retranslateUi(View_myreservation)
        QtCore.QMetaObject.connectSlotsByName(View_myreservation)

    def retranslateUi(self, View_myreservation):
        _translate = QtCore.QCoreApplication.translate
        View_myreservation.setWindowTitle(_translate("View_myreservation", "View_myreservation"))
        self.pushButton.setText(_translate("View_myreservation", "返回"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("View_myreservation", "预约教师"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("View_myreservation", "预约实验室"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("View_myreservation", "开始时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("View_myreservation", "结束时间"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("View_myreservation", "预约结果"))

    def setdata(self):
        self.query = Query()
        sql = "Select teacher_name,lab_name,re_time_start,re_time_end,re_result " \
              "FROM laboratory,teachers,reservation,users WHERE " \
              "reservation.labs_id = laboratory.labs_id and " \
              "reservation.account = users.account and " \
              "users.teacher_id = teachers.teacher_id and " \
              "reservation.account = '{}'".format(self.systemView.getaccount())
        results = self.query.fetch(sql)
        self.tableWidget.setRowCount(len(results))
        row = 0
        for i in results:
            newitem = QtWidgets.QTableWidgetItem(str(i[0]))
            self.tableWidget.setItem(row, 0, newitem)
            newitem = QtWidgets.QTableWidgetItem(str(i[1]))
            self.tableWidget.setItem(row, 1, newitem)
            newitem = QtWidgets.QTableWidgetItem(str(i[2]))
            self.tableWidget.setItem(row, 2, newitem)
            newitem = QtWidgets.QTableWidgetItem(str(i[3]))
            self.tableWidget.setItem(row, 3, newitem)
            if str(i[4])=="1":
                newitem = QtWidgets.QTableWidgetItem("已通过")
            else:
                newitem = QtWidgets.QTableWidgetItem("未通过")
            self.tableWidget.setItem(row, 4, newitem)
            row += 1