# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'View_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QDialog, QMessageBox

from Query import Query


class Ui_View_login(object):
    def __init__(self):
        self.query = None

    def setupUi(self, View_login, systemWindow, systemView):
        self.loginWindow = View_login
        self.systemWindow = systemWindow
        self.systemView = systemView

        View_login.setObjectName("View_login")
        View_login.resize(447, 292)
        View_login.setSizeGripEnabled(False)
        View_login.setModal(False)
        self.pushButton = QtWidgets.QPushButton(View_login)
        self.pushButton.setGeometry(QtCore.QRect(100, 210, 111, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(View_login)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 210, 121, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(View_login)
        self.lineEdit.setGeometry(QtCore.QRect(140, 80, 221, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(View_login)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 140, 221, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(View_login)
        self.label.setGeometry(QtCore.QRect(90, 90, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(View_login)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 31, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(View_login)
        QtCore.QMetaObject.connectSlotsByName(View_login)

        self.pushButton.clicked.connect(self.login)


    def retranslateUi(self, View_login):
        _translate = QtCore.QCoreApplication.translate
        View_login.setWindowTitle(_translate("View_login", "实验室管理系统"))
        self.pushButton.setText(_translate("View_login", "登陆"))
        self.pushButton_2.setText(_translate("View_login", "注册"))
        self.label.setText(_translate("View_login", "账号"))
        self.label_2.setText(_translate("View_login", "密码"))

    def login(self):
        self.query = Query()
        account = self.lineEdit.text()
        password = self.lineEdit_2.text()
        sql = 'SELECT account,password FROM users'
        results = self.query.fetch(sql)
        for i in results:
            if(account==i[0]):
                if(password==i[1]):
                    # todo
                    # 跳转到系统界面
                    self.systemView.setUserInformation(account)
                    self.systemWindow.show()
                    self.loginWindow.close()
                    return
                else:
                    msg_box = QMessageBox(QMessageBox.Warning, '密码错误', '请输入正确的密码')
                    msg_box.exec_()  # 执行弹出框
                    return
        msg_box = QMessageBox(QMessageBox.Warning, '账号不存在', '请先注册该账号')
        msg_box.exec_()  # 执行弹出框
        return





